### ISSUE TITLE
Add inheritancefree

### ISSUE THREAD

**Issue by ccostin93** [iwillfailyou/java-inspections#18]
Implement inheritancefree validation

**Comment by ccostin93** [comment]
@nikialeksey Can I do this? I already started looking into this when I was looking more into the JavaParser library.

1. The implementation will return all classes that extend other classes.
2. Interface inheritance will be ignored.
3. The only filter option is the standard `threshold` that exists for all rules.

**Comment by nikialeksey** [comment]
@ccostin93 Yes, why not? I would be glad to see your PR

inheritance - there is one problem: abstract classes. I don't like to use abstract classes, but I think nothing wrong with them. And in this inspections I would like to add filter option `skipAbstractClasses`, which would be skip inheritance from abstract classes, and architecture of `java-plugin` needs to be changed, because we need to accumulate project information, and then use it in our inspections.

**Comment by ccostin93** [comment]
@nikialeksey I created https://github.com/iwillfailyou/java-inspections/pull/25 just as a first implementation.

didn't get the chance to investigate `java-plugin` and what changes are required to actually make sending the project architecture to the inspection module. Still trying to get my bearing in all the separate repos and how they interact with one another.

**Comment by nikialeksey** [comment]
@ccostin93 Thanks! No problem, I have just created the #26
